//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AraviPortal.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AraviPortal.Shared.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoting innovation and new technologies for the ARAVI program..
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access To Publications.
        /// </summary>
        public static string AccessPublications {
            get {
                return ResourceManager.GetString("AccessPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator menu.
        /// </summary>
        public static string AdministratorMenu {
            get {
                return ResourceManager.GetString("AdministratorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Registration.
        /// </summary>
        public static string AdminRegister {
            get {
                return ResourceManager.GetString("AdminRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files have been uploaded!.
        /// </summary>
        public static string AllFilesUpload {
            get {
                return ResourceManager.GetString("AllFilesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor WebAssembly:.
        /// </summary>
        public static string Blazor {
            get {
                return ResourceManager.GetString("Blazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email, you can now log in to the system..
        /// </summary>
        public static string ConfirmedEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to confirm your account..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course menu.
        /// </summary>
        public static string CourseMenu {
            get {
                return ResourceManager.GetString("CourseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daily data upload has been completed..
        /// </summary>
        public static string DailyDataUpload {
            get {
                return ResourceManager.GetString("DailyDataUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB file upload successful. Starting data update process....
        /// </summary>
        public static string DailyProcessingStarted {
            get {
                return ResourceManager.GetString("DailyProcessingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database administrator.
        /// </summary>
        public static string DatabaseAdmin {
            get {
                return ResourceManager.GetString("DatabaseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving to the database: {0}.
        /// </summary>
        public static string DatabaseSaveError {
            get {
                return ResourceManager.GetString("DatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the {0}: {1}?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software administrator.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Profile.
        /// </summary>
        public static string EditUserProfile {
            get {
                return ResourceManager.GetString("EditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered already exists..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string ERR_Unexpected {
            get {
                return ResourceManager.GetString("ERR_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted because it has related records..
        /// </summary>
        public static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you are trying to create already exists..
        /// </summary>
        public static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city Id is not valid..
        /// </summary>
        public static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hangar Id is not valid..
        /// </summary>
        public static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base Id is not valid..
        /// </summary>
        public static string ERR005A {
            get {
                return ResourceManager.GetString("ERR005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hangar Id is not valid..
        /// </summary>
        public static string ERR005B {
            get {
                return ResourceManager.GetString("ERR005B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of attempts, your account is blocked, please try again in 5 minutes..
        /// </summary>
        public static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has not been enabled, you must follow the instructions in the email sent to enable the user..
        /// </summary>
        public static string ERR008 {
            get {
                return ResourceManager.GetString("ERR008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user Id is not valid..
        /// </summary>
        public static string ERR009 {
            get {
                return ResourceManager.GetString("ERR009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been selected..
        /// </summary>
        public static string ERR010 {
            get {
                return ResourceManager.GetString("ERR010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not supported. Please upload an .xlsx or .csv file..
        /// </summary>
        public static string ERR011 {
            get {
                return ResourceManager.GetString("ERR011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the spreadsheet has not been provided..
        /// </summary>
        public static string ERR012 {
            get {
                return ResourceManager.GetString("ERR012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting Excel file to CSV: {0}.
        /// </summary>
        public static string ERR013 {
            get {
                return ResourceManager.GetString("ERR013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to perform this operation..
        /// </summary>
        public static string ERR401 {
            get {
                return ResourceManager.GetString("ERR401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this operation..
        /// </summary>
        public static string ERR403 {
            get {
                return ResourceManager.GetString("ERR403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string ERR404 {
            get {
                return ResourceManager.GetString("ERR404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not selected.
        /// </summary>
        public static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selected:.
        /// </summary>
        public static string FileSelected {
            get {
                return ResourceManager.GetString("FileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading file: {0}.
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully and data saved to the database!.
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string FileUploadUnexpectedError {
            get {
                return ResourceManager.GetString("FileUploadUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you forgotten your password?.
        /// </summary>
        public static string ForgottenYourPassword {
            get {
                return ResourceManager.GetString("ForgottenYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangar.
        /// </summary>
        public static string Hangar {
            get {
                return ResourceManager.GetString("Hangar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangars.
        /// </summary>
        public static string Hangars {
            get {
                return ResourceManager.GetString("Hangars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources.
        /// </summary>
        public static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important note.
        /// </summary>
        public static string ImportantNote {
            get {
                return ResourceManager.GetString("ImportantNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is correct.
        /// </summary>
        public static string IsCorrect {
            get {
                return ResourceManager.GetString("IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Awareness Training.
        /// </summary>
        public static string ITAwarenessTraining {
            get {
                return ResourceManager.GetString("ITAwarenessTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT course.
        /// </summary>
        public static string ITcourse {
            get {
                return ResourceManager.GetString("ITcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave the page and lose your changes?.
        /// </summary>
        public static string LeaveAndLoseChanges {
            get {
                return ResourceManager.GetString("LeaveAndLoseChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be between {2} and {1} characters..
        /// </summary>
        public static string LengthField {
            get {
                return ResourceManager.GetString("LengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Correctly.
        /// </summary>
        public static string LoadedCorrectly {
            get {
                return ResourceManager.GetString("LoadedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string Logistics {
            get {
                return ResourceManager.GetString("Logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you log out, you will need to log back in to access your account..
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail forwarding.
        /// </summary>
        public static string MailForwarding {
            get {
                return ResourceManager.GetString("MailForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} cannot be longer than {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS menu.
        /// </summary>
        public static string MenuSIS {
            get {
                return ResourceManager.GetString("MenuSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu upload data.
        /// </summary>
        public static string MenuUploadData {
            get {
                return ResourceManager.GetString("MenuUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must have at least {1} characters..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At AMENTUM, our mission is to provide advanced engineering and technology solutions to the most important challenges in science, security, and sustainability. Our vision is to create a secure and vibrant future..
        /// </summary>
        public static string MissionVision {
            get {
                return ResourceManager.GetString("MissionVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission, Vision, and Values.
        /// </summary>
        public static string MissionVisionValues {
            get {
                return ResourceManager.GetString("MissionVisionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MRO Backlog file set has been processed successfully..
        /// </summary>
        public static string MROBacklogFilesUpload {
            get {
                return ResourceManager.GetString("MROBacklogFilesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor:.
        /// </summary>
        public static string MudBlazor {
            get {
                return ResourceManager.GetString("MudBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET9:.
        /// </summary>
        public static string Net9 {
            get {
                return ResourceManager.GetString("Net9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New2 {
            get {
                return ResourceManager.GetString("New2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next video.
        /// </summary>
        public static string NextVideo {
            get {
                return ResourceManager.GetString("NextVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to show....
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this content....
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is nothing on this route..
        /// </summary>
        public static string NothingInRoute {
            get {
                return ResourceManager.GetString("NothingInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a user yet? Register here.
        /// </summary>
        public static string NotUserYet {
            get {
                return ResourceManager.GetString("NotUserYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind every successful project is a team of passionate professionals. In the IT department, we have experts in software development, business consulting, and user experience design, all dedicated to providing IT solutions that are at the forefront of new technologies. We believe in collaboration, continuous learning, and delivering results that exceed expectations..
        /// </summary>
        public static string OurTeamText {
            get {
                return ResourceManager.GetString("OurTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation are not the same..
        /// </summary>
        public static string PasswordAndConfirmationDifferent {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password changed successfully, you can now log in with your new password..
        /// </summary>
        public static string PasswordRecoveredMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone  Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PII and cybersecurity.
        /// </summary>
        public static string PIIandCybersecurity {
            get {
                return ResourceManager.GetString("PIIandCybersecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI.
        /// </summary>
        public static string PowerBi {
            get {
                return ResourceManager.GetString("PowerBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous video.
        /// </summary>
        public static string PreviousVideo {
            get {
                return ResourceManager.GetString("PreviousVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        public static string Procurement {
            get {
                return ResourceManager.GetString("Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Control.
        /// </summary>
        public static string ProductionControl {
            get {
                return ResourceManager.GetString("ProductionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program information storage..
        /// </summary>
        public static string ProgramInformationStorage {
            get {
                return ResourceManager.GetString("ProgramInformationStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance.
        /// </summary>
        public static string QualityAssurance {
            get {
                return ResourceManager.GetString("QualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string QualityControl {
            get {
                return ResourceManager.GetString("QualityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of question.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record created successfully.
        /// </summary>
        public static string RecordCreatedOk {
            get {
                return ResourceManager.GetString("RecordCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully.
        /// </summary>
        public static string RecordDeletedOk {
            get {
                return ResourceManager.GetString("RecordDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully.
        /// </summary>
        public static string RecordSavedOk {
            get {
                return ResourceManager.GetString("RecordSavedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Number:.
        /// </summary>
        public static string RecordsNumber {
            get {
                return ResourceManager.GetString("RecordsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to you with instructions on how to recover your password..
        /// </summary>
        public static string RecoverPasswordMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend account activation email.
        /// </summary>
        public static string ResendAccountActivationEmail {
            get {
                return ResourceManager.GetString("ResendAccountActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChanges.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a Base ---.
        /// </summary>
        public static string SelectABase {
            get {
                return ResourceManager.GetString("SelectABase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a City ---.
        /// </summary>
        public static string SelectACity {
            get {
                return ResourceManager.GetString("SelectACity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a Country ---.
        /// </summary>
        public static string SelectACountry {
            get {
                return ResourceManager.GetString("SelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a Hangar ---.
        /// </summary>
        public static string SelectAHangar {
            get {
                return ResourceManager.GetString("SelectAHangar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file....
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to upload..
        /// </summary>
        public static string SelectFileExcel {
            get {
                return ResourceManager.GetString("SelectFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully. An email has been sent to you with instructions on how to activate your account..
        /// </summary>
        public static string SendEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("SendEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint: Your official backup.
        /// </summary>
        public static string SharePointStorage {
            get {
                return ResourceManager.GetString("SharePointStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.I.S..
        /// </summary>
        public static string SIS {
            get {
                return ResourceManager.GetString("SIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Integration Software.
        /// </summary>
        public static string SISName {
            get {
                return ResourceManager.GetString("SISName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRAA.
        /// </summary>
        public static string SRAA {
            get {
                return ResourceManager.GetString("SRAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Analysis Recording System.
        /// </summary>
        public static string SRAAName {
            get {
                return ResourceManager.GetString("SRAAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start course.
        /// </summary>
        public static string StartCourse {
            get {
                return ResourceManager.GetString("StartCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        public static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARAVI Program Applications Portal.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text option.
        /// </summary>
        public static string TextOption {
            get {
                return ResourceManager.GetString("TextOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARAVI Portal.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload backlog report.
        /// </summary>
        public static string UploadBacklog {
            get {
                return ResourceManager.GetString("UploadBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload daily files.
        /// </summary>
        public static string Uploaddaily {
            get {
                return ResourceManager.GetString("Uploaddaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded File.
        /// </summary>
        public static string UploadedFile {
            get {
                return ResourceManager.GetString("UploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file, please wait....
        /// </summary>
        public static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload monthly files.
        /// </summary>
        public static string Uploadmonthly {
            get {
                return ResourceManager.GetString("Uploadmonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Receiving Report.
        /// </summary>
        public static string UploadReceiving {
            get {
                return ResourceManager.GetString("UploadReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Shipping Report.
        /// </summary>
        public static string UploadShipping {
            get {
                return ResourceManager.GetString("UploadShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Summary AWB.
        /// </summary>
        public static string UploadSummary {
            get {
                return ResourceManager.GetString("UploadSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload UCS AMMS.
        /// </summary>
        public static string UploadUCSAMMS {
            get {
                return ResourceManager.GetString("UploadUCSAMMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload W Buyer file.
        /// </summary>
        public static string UploadWBuyer {
            get {
                return ResourceManager.GetString("UploadWBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload W Program file.
        /// </summary>
        public static string UploadWProgram {
            get {
                return ResourceManager.GetString("UploadWProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload W Supplier file.
        /// </summary>
        public static string UploadWSupplier {
            get {
                return ResourceManager.GetString("UploadWSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        public static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        public static string UserRegister {
            get {
                return ResourceManager.GetString("UserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value False/True.
        /// </summary>
        public static string ValueFalseTrue {
            get {
                return ResourceManager.GetString("ValueFalseTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our core values are:.
        /// </summary>
        public static string ValueText {
            get {
                return ResourceManager.GetString("ValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We realize breakthroughs by continuously reinventing..
        /// </summary>
        public static string ValueText1 {
            get {
                return ResourceManager.GetString("ValueText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver on missions by meeting every commitment..
        /// </summary>
        public static string ValueText2 {
            get {
                return ResourceManager.GetString("ValueText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We take on challenges with courage..
        /// </summary>
        public static string ValueText3 {
            get {
                return ResourceManager.GetString("ValueText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We embrace collaboration &amp; employee engagement..
        /// </summary>
        public static string ValueText4 {
            get {
                return ResourceManager.GetString("ValueText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W buyer.
        /// </summary>
        public static string WBuyer {
            get {
                return ResourceManager.GetString("WBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the IT awareness course..
        /// </summary>
        public static string WelcomeCourse {
            get {
                return ResourceManager.GetString("WelcomeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What makes us different? Cutting-edge technology..
        /// </summary>
        public static string WhatDifferent {
            get {
                return ResourceManager.GetString("WhatDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What really sets us apart at AMENTUM is our focus on technological innovation and user experience.
        ///We develop our solutions using the most modern and robust platforms:.
        /// </summary>
        public static string WhatDifferentText {
            get {
                return ResourceManager.GetString("WhatDifferentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We leverage the latest version of the .NET platform to build secure, scalable, and high-performance applications..
        /// </summary>
        public static string WhatDifferentText1 {
            get {
                return ResourceManager.GetString("WhatDifferentText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer interactive and fast web experiences, directly in the browser, with the power and reach of C# code..
        /// </summary>
        public static string WhatDifferentText2 {
            get {
                return ResourceManager.GetString("WhatDifferentText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We create modern, intuitive, and responsive user interfaces, ensuring that our applications are easy to use and visually appealing on any device..
        /// </summary>
        public static string WhatDifferentText3 {
            get {
                return ResourceManager.GetString("WhatDifferentText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This technological combination allows us to deliver agile, efficient, and future-proof solutions, ensuring that your technology investment is long-lasting and effective..
        /// </summary>
        public static string WhatDifferentTextB {
            get {
                return ResourceManager.GetString("WhatDifferentTextB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Update.
        /// </summary>
        public static string Workflowupdate {
            get {
                return ResourceManager.GetString("Workflowupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheet named {0} was not found..
        /// </summary>
        public static string WorkSheetNotFound {
            get {
                return ResourceManager.GetString("WorkSheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W program.
        /// </summary>
        public static string WProgram {
            get {
                return ResourceManager.GetString("WProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file format.
        /// </summary>
        public static string WrongFileFormat {
            get {
                return ResourceManager.GetString("WrongFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W supplier.
        /// </summary>
        public static string WSupplier {
            get {
                return ResourceManager.GetString("WSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
