// <auto-generated />
using System;
using AraviPortal.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AraviPortal.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250815163442_AddSISWBuyerEntity")]
    partial class AddSISWBuyerEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AraviPortal.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.CorrectAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("ValueFalseTrue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("CorrectAnswers");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Hangar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.ToTable("Hangars");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("TextOption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasMaxLength(500)
                        .HasColumnType("int");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.SISUcsAmms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("alternatepn_SISUcsAmms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alternatepn_SISUcsAmms");

                    b.Property<string>("appremarks_SISUcsAmms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("appremarks_SISUcsAmms");

                    b.Property<string>("awb_SISUcsAmms")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("awb_SISUcsAmms");

                    b.Property<string>("budgete_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("budgete_SISUcsAmms");

                    b.Property<string>("buyer_SISUcsAmms")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("buyer_SISUcsAmms");

                    b.Property<string>("company_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("company_SISUcsAmms");

                    b.Property<DateTime?>("createdinmro_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdinmro_SISUcsAmms");

                    b.Property<DateTime?>("dateexptovendor_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateexptovendor_SISUcsAmms");

                    b.Property<DateTime?>("datercvdapp_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("datercvdapp_SISUcsAmms");

                    b.Property<DateTime?>("datesentapp_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("datesentapp_SISUcsAmms");

                    b.Property<string>("description_SISUcsAmms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_SISUcsAmms");

                    b.Property<int?>("earecinffinbound_SISUcsAmms")
                        .HasColumnType("int")
                        .HasColumnName("earecinffinbound_SISUcsAmms");

                    b.Property<DateTime?>("edd_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("edd_SISUcsAmms");

                    b.Property<string>("enduse_SISUcsAmms")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("enduse_SISUcsAmms");

                    b.Property<DateTime?>("estdatedeparturet4_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("estdatedeparturet4_SISUcsAmms");

                    b.Property<decimal?>("extendcost_SISUcsAmms")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("extendcost_SISUcsAmms");

                    b.Property<string>("lasteditedby_SISUcsAmms")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("lasteditedby_SISUcsAmms");

                    b.Property<string>("logremarks_SISUcsAmms")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("logremarks_SISUcsAmms");

                    b.Property<string>("name_SISUcsAmms")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name_SISUcsAmms");

                    b.Property<string>("orderstatus_SISUcsAmms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("orderstatus_SISUcsAmms");

                    b.Property<decimal?>("partinvcost_SISUcsAmms")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("partinvcost_SISUcsAmms");

                    b.Property<string>("partnumber_SISUcsAmms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("partnumber_SISUcsAmms");

                    b.Property<DateTime?>("podate_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("podate_SISUcsAmms");

                    b.Property<string>("ponumber_SISUcsAmms")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ponumber_SISUcsAmms");

                    b.Property<string>("priority_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority_SISUcsAmms");

                    b.Property<string>("purchasecondition_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("purchasecondition_SISUcsAmms");

                    b.Property<string>("purchaseunit_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("purchaseunit_SISUcsAmms");

                    b.Property<decimal?>("pureqqty_SISUcsAmms")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pureqqty_SISUcsAmms");

                    b.Property<DateTime?>("receiveddateff_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("receiveddateff_SISUcsAmms");

                    b.Property<string>("repremarks_SISUcsAmms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("repremarks_SISUcsAmms");

                    b.Property<string>("requestedby_SISUcsAmms")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requestedby_SISUcsAmms");

                    b.Property<DateTime?>("requireddate_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("requireddate_SISUcsAmms");

                    b.Property<string>("requisition_SISUcsAmms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("requisition_SISUcsAmms");

                    b.Property<DateTime?>("requisitiondate_SISUcsAmms")
                        .HasColumnType("datetime2")
                        .HasColumnName("requisitiondate_SISUcsAmms");

                    b.Property<string>("site_SISUcsAmms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("site_SISUcsAmms");

                    b.Property<string>("sn_SISUcsAmms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sn_SISUcsAmms");

                    b.Property<string>("type_SISUcsAmms")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type_SISUcsAmms");

                    b.Property<string>("vendorcode_SISUcsAmms")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("vendorcode_SISUcsAmms");

                    b.Property<string>("vendorname_SISUcsAmms")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("vendorname_SISUcsAmms");

                    b.HasKey("Id");

                    b.ToTable("SISUcsAmms");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.SISWBuyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("aog_SISWBuyer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("aog_SISWBuyer");

                    b.Property<DateTime?>("approveddate_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("approveddate_SISWBuyer");

                    b.Property<string>("bostatus_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bostatus_SISWBuyer");

                    b.Property<string>("buyer_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("buyer_SISWBuyer");

                    b.Property<string>("category_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_SISWBuyer");

                    b.Property<string>("cpacct_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cpacct_SISWBuyer");

                    b.Property<int?>("daysapproved_SISWBuyer")
                        .HasColumnType("int")
                        .HasColumnName("daysapproved_SISWBuyer");

                    b.Property<string>("description_SISWBuyer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_SISWBuyer");

                    b.Property<string>("dodn_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dodn_SISWBuyer");

                    b.Property<decimal?>("dueqty_SISWBuyer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dueqty_SISWBuyer");

                    b.Property<DateTime?>("edd_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("edd_SISWBuyer");

                    b.Property<decimal?>("estimatedtotalpricedue_SISWBuyer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimatedtotalpricedue_SISWBuyer");

                    b.Property<decimal?>("estimatedunitprice_SISWBuyer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimatedunitprice_SISWBuyer");

                    b.Property<string>("jcn_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("jcn_SISWBuyer");

                    b.Property<string>("maintcontrolno_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maintcontrolno_SISWBuyer");

                    b.Property<string>("markfor_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("markfor_SISWBuyer");

                    b.Property<string>("niin_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("niin_SISWBuyer");

                    b.Property<string>("niinuom_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("niinuom_SISWBuyer");

                    b.Property<string>("notes_SISWBuyer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes_SISWBuyer");

                    b.Property<string>("obligated_SISWBuyer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("obligated_SISWBuyer");

                    b.Property<DateTime?>("orddate_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("orddate_SISWBuyer");

                    b.Property<decimal?>("ordqty_SISWBuyer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ordqty_SISWBuyer");

                    b.Property<string>("orgid_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("orgid_SISWBuyer");

                    b.Property<string>("partnumber_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("partnumber_SISWBuyer");

                    b.Property<decimal?>("percent_SISWBuyer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percent_SISWBuyer");

                    b.Property<int?>("polinenumber_SISWBuyer")
                        .HasColumnType("int")
                        .HasColumnName("polinenumber_SISWBuyer");

                    b.Property<string>("polinestatus_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("polinestatus_SISWBuyer");

                    b.Property<string>("ponumber_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ponumber_SISWBuyer");

                    b.Property<string>("potype_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("potype_SISWBuyer");

                    b.Property<string>("pouom_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pouom_SISWBuyer");

                    b.Property<string>("pricetype_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pricetype_SISWBuyer");

                    b.Property<string>("priority_SISWBuyer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority_SISWBuyer");

                    b.Property<string>("projectid_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("projectid_SISWBuyer");

                    b.Property<DateTime?>("quoteduedateutc_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("quoteduedateutc_SISWBuyer");

                    b.Property<DateTime?>("rdd_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("rdd_SISWBuyer");

                    b.Property<string>("reqgroupno_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reqgroupno_SISWBuyer");

                    b.Property<string>("requestedby_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requestedby_SISWBuyer");

                    b.Property<string>("requesttype_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requesttype_SISWBuyer");

                    b.Property<string>("rvsc_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rvsc_SISWBuyer");

                    b.Property<string>("serialnumber_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("serialnumber_SISWBuyer");

                    b.Property<string>("shippingno_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shippingno_SISWBuyer");

                    b.Property<string>("siteawb_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("siteawb_SISWBuyer");

                    b.Property<string>("siteid_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("siteid_SISWBuyer");

                    b.Property<DateTime?>("siteshippeddate_SISWBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("siteshippeddate_SISWBuyer");

                    b.Property<string>("source_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_SISWBuyer");

                    b.Property<string>("vendorid_SISWBuyer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vendorid_SISWBuyer");

                    b.Property<string>("vendorname_SISWBuyer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vendorname_SISWBuyer");

                    b.HasKey("Id");

                    b.ToTable("SISWBuyer");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.SISWProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("aog_SISWProgram")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("aog_SISWProgram");

                    b.Property<string>("bostatus_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bostatus_SISWProgram");

                    b.Property<string>("category_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_SISWProgram");

                    b.Property<string>("cpacct_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cpacct_SISWProgram");

                    b.Property<int?>("daysaging_SISWProgram")
                        .HasColumnType("int")
                        .HasColumnName("daysaging_SISWProgram");

                    b.Property<string>("description_SISWProgram")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_SISWProgram");

                    b.Property<string>("dodn_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dodn_SISWProgram");

                    b.Property<decimal?>("estunitprice_SISWProgram")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estunitprice_SISWProgram");

                    b.Property<string>("jcn_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("jcn_SISWProgram");

                    b.Property<decimal?>("lineprice_SISWProgram")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("lineprice_SISWProgram");

                    b.Property<string>("maintcontrolno_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maintcontrolno_SISWProgram");

                    b.Property<string>("markfor_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("markfor_SISWProgram");

                    b.Property<int?>("ordQty_SISWProgram")
                        .HasColumnType("int")
                        .HasColumnName("ordQty_SISWProgram");

                    b.Property<string>("orgid_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("orgid_SISWProgram");

                    b.Property<string>("partnumber_SISWProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("partnumber_SISWProgram");

                    b.Property<decimal?>("percent_SISWProgram")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percent_SISWProgram");

                    b.Property<string>("ponumber_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ponumber_SISWProgram");

                    b.Property<string>("priority_SISWProgram")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("priority_SISWProgram");

                    b.Property<string>("projectid_SISWProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("projectid_SISWProgram");

                    b.Property<DateTime?>("rejecteddate_SISWProgram")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejecteddate_SISWProgram");

                    b.Property<string>("rejectnotes_SISWProgram")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejectnotes_SISWProgram");

                    b.Property<string>("requestedby_SISWProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("requestedby_SISWProgram");

                    b.Property<string>("shippingno_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shippingno_SISWProgram");

                    b.Property<string>("siteid_SISWProgram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("siteid_SISWProgram");

                    b.Property<string>("source_SISWProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_SISWProgram");

                    b.HasKey("Id");

                    b.ToTable("SISWProgram");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.CorrectAnswer", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AraviPortal.Shared.Entities.Question", "Question")
                        .WithOne("CorrectAnswer")
                        .HasForeignKey("AraviPortal.Shared.Entities.CorrectAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Hangar", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.City", "City")
                        .WithMany("Hangars")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Option", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Question", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.User", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AraviPortal.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AraviPortal.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.City", b =>
                {
                    b.Navigation("Hangars");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AraviPortal.Shared.Entities.Question", b =>
                {
                    b.Navigation("CorrectAnswer");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
